import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from "../store/ReduxProvider";


const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutType = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${montserrat.variable}`}>
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
